// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/SvetlovA/lampa/backend/pkg/storage"
)

// StoreMock is a mock implementation of storage.Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked storage.Store
//		mockedStore := &StoreMock{
//			DeleteFunc: func(ctx context.Context, userID string) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, userID string) (storage.Record, error) {
//				panic("mock out the Get method")
//			},
//			UpsertFunc: func(ctx context.Context, rec storage.Record) (storage.Record, error) {
//				panic("mock out the Upsert method")
//			},
//		}
//
//		// use mockedStore in code that requires storage.Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, userID string) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, userID string) (storage.Record, error)

	// UpsertFunc mocks the Upsert method.
	UpsertFunc func(ctx context.Context, rec storage.Record) (storage.Record, error)

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
		}
		// Upsert holds details about calls to the Upsert method.
		Upsert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Rec is the rec argument value.
			Rec storage.Record
		}
	}
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockUpsert sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *StoreMock) Delete(ctx context.Context, userID string) error {
	if mock.DeleteFunc == nil {
		panic("StoreMock.DeleteFunc: method is nil but Store.Delete was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, userID)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedStore.DeleteCalls())
func (mock *StoreMock) DeleteCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *StoreMock) Get(ctx context.Context, userID string) (storage.Record, error) {
	if mock.GetFunc == nil {
		panic("StoreMock.GetFunc: method is nil but Store.Get was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, userID)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedStore.GetCalls())
func (mock *StoreMock) GetCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Upsert calls UpsertFunc.
func (mock *StoreMock) Upsert(ctx context.Context, rec storage.Record) (storage.Record, error) {
	if mock.UpsertFunc == nil {
		panic("StoreMock.UpsertFunc: method is nil but Store.Upsert was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Rec storage.Record
	}{
		Ctx: ctx,
		Rec: rec,
	}
	mock.lockUpsert.Lock()
	mock.calls.Upsert = append(mock.calls.Upsert, callInfo)
	mock.lockUpsert.Unlock()
	return mock.UpsertFunc(ctx, rec)
}

// UpsertCalls gets all the calls that were made to Upsert.
// Check the length with:
//
//	len(mockedStore.UpsertCalls())
func (mock *StoreMock) UpsertCalls() []struct {
	Ctx context.Context
	Rec storage.Record
} {
	var calls []struct {
		Ctx context.Context
		Rec storage.Record
	}
	mock.lockUpsert.RLock()
	calls = mock.calls.Upsert
	mock.lockUpsert.RUnlock()
	return calls
}
