// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/SvetlovA/lampa/backend/pkg/storage"
)

// UserDataMock is a mock implementation of api.UserData.
//
//	func TestSomethingThatUsesUserData(t *testing.T) {
//
//		// make and configure a mocked api.UserData
//		mockedUserData := &UserDataMock{
//			DeleteFunc: func(ctx context.Context, userID string) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, userID string) (storage.Document, error) {
//				panic("mock out the Get method")
//			},
//			ReplaceFunc: func(ctx context.Context, userID string, raw []byte) (storage.Document, error) {
//				panic("mock out the Replace method")
//			},
//		}
//
//		// use mockedUserData in code that requires api.UserData
//		// and then make assertions.
//
//	}
type UserDataMock struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, userID string) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, userID string) (storage.Document, error)

	// ReplaceFunc mocks the Replace method.
	ReplaceFunc func(ctx context.Context, userID string, raw []byte) (storage.Document, error)

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
		}
		// Replace holds details about calls to the Replace method.
		Replace []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// Raw is the raw argument value.
			Raw []byte
		}
	}
	lockDelete  sync.RWMutex
	lockGet     sync.RWMutex
	lockReplace sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *UserDataMock) Delete(ctx context.Context, userID string) error {
	if mock.DeleteFunc == nil {
		panic("UserDataMock.DeleteFunc: method is nil but UserData.Delete was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, userID)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedUserData.DeleteCalls())
func (mock *UserDataMock) DeleteCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *UserDataMock) Get(ctx context.Context, userID string) (storage.Document, error) {
	if mock.GetFunc == nil {
		panic("UserDataMock.GetFunc: method is nil but UserData.Get was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, userID)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedUserData.GetCalls())
func (mock *UserDataMock) GetCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Replace calls ReplaceFunc.
func (mock *UserDataMock) Replace(ctx context.Context, userID string, raw []byte) (storage.Document, error) {
	if mock.ReplaceFunc == nil {
		panic("UserDataMock.ReplaceFunc: method is nil but UserData.Replace was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
		Raw    []byte
	}{
		Ctx:    ctx,
		UserID: userID,
		Raw:    raw,
	}
	mock.lockReplace.Lock()
	mock.calls.Replace = append(mock.calls.Replace, callInfo)
	mock.lockReplace.Unlock()
	return mock.ReplaceFunc(ctx, userID, raw)
}

// ReplaceCalls gets all the calls that were made to Replace.
// Check the length with:
//
//	len(mockedUserData.ReplaceCalls())
func (mock *UserDataMock) ReplaceCalls() []struct {
	Ctx    context.Context
	UserID string
	Raw    []byte
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
		Raw    []byte
	}
	mock.lockReplace.RLock()
	calls = mock.calls.Replace
	mock.lockReplace.RUnlock()
	return calls
}
